-- MySQL Script generated by MySQL Workbench
-- Sat 05 Sep 2015 06:54:50 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestor` ;
USE `gestor` ;

-- -----------------------------------------------------
-- Table `gestor`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor`.`alumnos` (
  `matricula` INT(10) NOT NULL COMMENT '',
  `apellido_p` VARCHAR(45) NULL COMMENT '',
  `apellido_m` VARCHAR(45) NULL COMMENT '',
  `fecha_nacimiento` DATE NULL COMMENT '',
  `fecha_ingreso` DATE NULL COMMENT '',
  `genero` VARCHAR(1) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `carrera` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`matricula`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor`.`tutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor`.`tutores` (
  `clave_prof` INT(10) NOT NULL COMMENT '',
  `apellido_p` VARCHAR(45) NULL COMMENT '',
  `apellido_m` VARCHAR(45) NULL COMMENT '',
  `genero` VARCHAR(1) NULL COMMENT '',
  `area` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`clave_prof`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre_usuario` VARCHAR(45) NOT NULL COMMENT '',
  `clave` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
